// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/email_audit.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuleType int32

const (
	RuleType_REGEX_BASED   RuleType = 0 // Rule based on regex patterns
	RuleType_ML_BASED      RuleType = 1 // Rule using ML classification
	RuleType_KEYWORD_BASED RuleType = 2 // Rule matching keywords
	RuleType_CUSTOM_LOGIC  RuleType = 3 // Rule using custom logic implementation
)

// Enum value maps for RuleType.
var (
	RuleType_name = map[int32]string{
		0: "REGEX_BASED",
		1: "ML_BASED",
		2: "KEYWORD_BASED",
		3: "CUSTOM_LOGIC",
	}
	RuleType_value = map[string]int32{
		"REGEX_BASED":   0,
		"ML_BASED":      1,
		"KEYWORD_BASED": 2,
		"CUSTOM_LOGIC":  3,
	}
)

func (x RuleType) Enum() *RuleType {
	p := new(RuleType)
	*p = x
	return p
}

func (x RuleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuleType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_email_audit_proto_enumTypes[0].Descriptor()
}

func (RuleType) Type() protoreflect.EnumType {
	return &file_proto_email_audit_proto_enumTypes[0]
}

func (x RuleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuleType.Descriptor instead.
func (RuleType) EnumDescriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{0}
}

type EmailAuditRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EmailId       string                 `protobuf:"bytes,2,opt,name=email_id,json=emailId,proto3" json:"email_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	EmailContent  []byte                 `protobuf:"bytes,5,opt,name=email_content,json=emailContent,proto3" json:"email_content,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAuditRequest) Reset() {
	*x = EmailAuditRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAuditRequest) ProtoMessage() {}

func (x *EmailAuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAuditRequest.ProtoReflect.Descriptor instead.
func (*EmailAuditRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{0}
}

func (x *EmailAuditRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EmailAuditRequest) GetEmailId() string {
	if x != nil {
		return x.EmailId
	}
	return ""
}

func (x *EmailAuditRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *EmailAuditRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EmailAuditRequest) GetEmailContent() []byte {
	if x != nil {
		return x.EmailContent
	}
	return nil
}

func (x *EmailAuditRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type EmailAuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailAuditResponse) Reset() {
	*x = EmailAuditResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailAuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailAuditResponse) ProtoMessage() {}

func (x *EmailAuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailAuditResponse.ProtoReflect.Descriptor instead.
func (*EmailAuditResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{1}
}

func (x *EmailAuditResponse) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *EmailAuditResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EmailAuditResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetAuditReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditReportRequest) Reset() {
	*x = GetAuditReportRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditReportRequest) ProtoMessage() {}

func (x *GetAuditReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditReportRequest.ProtoReflect.Descriptor instead.
func (*GetAuditReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuditReportRequest) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *GetAuditReportRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAuditReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *AuditReport           `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditReportResponse) Reset() {
	*x = GetAuditReportResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditReportResponse) ProtoMessage() {}

func (x *GetAuditReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditReportResponse.ProtoReflect.Descriptor instead.
func (*GetAuditReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{3}
}

func (x *GetAuditReportResponse) GetReport() *AuditReport {
	if x != nil {
		return x.Report
	}
	return nil
}

func (x *GetAuditReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetAuditSummaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditSummaryRequest) Reset() {
	*x = GetAuditSummaryRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditSummaryRequest) ProtoMessage() {}

func (x *GetAuditSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetAuditSummaryRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{4}
}

func (x *GetAuditSummaryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetAuditSummaryRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *GetAuditSummaryRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAuditSummaryRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type GetAuditSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*AuditReport         `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditSummaryResponse) Reset() {
	*x = GetAuditSummaryResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditSummaryResponse) ProtoMessage() {}

func (x *GetAuditSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetAuditSummaryResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{5}
}

func (x *GetAuditSummaryResponse) GetReports() []*AuditReport {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *GetAuditSummaryResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *GetAuditSummaryResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetAuditSummaryResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type RulesEvaluationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RuleSet       []*Rule                `protobuf:"bytes,3,rep,name=rule_set,json=ruleSet,proto3" json:"rule_set,omitempty"`
	EmailThread   *EmailThread           `protobuf:"bytes,4,opt,name=email_thread,json=emailThread,proto3" json:"email_thread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RulesEvaluationRequest) Reset() {
	*x = RulesEvaluationRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RulesEvaluationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesEvaluationRequest) ProtoMessage() {}

func (x *RulesEvaluationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesEvaluationRequest.ProtoReflect.Descriptor instead.
func (*RulesEvaluationRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{6}
}

func (x *RulesEvaluationRequest) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *RulesEvaluationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RulesEvaluationRequest) GetRuleSet() []*Rule {
	if x != nil {
		return x.RuleSet
	}
	return nil
}

func (x *RulesEvaluationRequest) GetEmailThread() *EmailThread {
	if x != nil {
		return x.EmailThread
	}
	return nil
}

type RulesEvaluationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	Evaluations   []*RuleEvaluation      `protobuf:"bytes,2,rep,name=evaluations,proto3" json:"evaluations,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RulesEvaluationResponse) Reset() {
	*x = RulesEvaluationResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RulesEvaluationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RulesEvaluationResponse) ProtoMessage() {}

func (x *RulesEvaluationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RulesEvaluationResponse.ProtoReflect.Descriptor instead.
func (*RulesEvaluationResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{7}
}

func (x *RulesEvaluationResponse) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *RulesEvaluationResponse) GetEvaluations() []*RuleEvaluation {
	if x != nil {
		return x.Evaluations
	}
	return nil
}

func (x *RulesEvaluationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleRequest) Reset() {
	*x = AddRuleRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleRequest) ProtoMessage() {}

func (x *AddRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleRequest.ProtoReflect.Descriptor instead.
func (*AddRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{8}
}

func (x *AddRuleRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *AddRuleRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type AddRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRuleResponse) Reset() {
	*x = AddRuleResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRuleResponse) ProtoMessage() {}

func (x *AddRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRuleResponse.ProtoReflect.Descriptor instead.
func (*AddRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{9}
}

func (x *AddRuleResponse) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *AddRuleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *Rule                  `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleRequest) Reset() {
	*x = UpdateRuleRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleRequest) ProtoMessage() {}

func (x *UpdateRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateRuleRequest) GetRule() *Rule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *UpdateRuleRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type UpdateRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRuleResponse) Reset() {
	*x = UpdateRuleResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRuleResponse) ProtoMessage() {}

func (x *UpdateRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRuleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateRuleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type DeleteRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	CompanyId     string                 `protobuf:"bytes,2,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleRequest) Reset() {
	*x = DeleteRuleRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleRequest) ProtoMessage() {}

func (x *DeleteRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRuleRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteRuleRequest) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *DeleteRuleRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

type DeleteRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRuleResponse) Reset() {
	*x = DeleteRuleResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRuleResponse) ProtoMessage() {}

func (x *DeleteRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRuleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRuleResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteRuleResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CompanyId     string                 `protobuf:"bytes,1,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	EnabledOnly   bool                   `protobuf:"varint,3,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesRequest) Reset() {
	*x = ListRulesRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesRequest) ProtoMessage() {}

func (x *ListRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesRequest.ProtoReflect.Descriptor instead.
func (*ListRulesRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{14}
}

func (x *ListRulesRequest) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *ListRulesRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListRulesRequest) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

type ListRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*Rule                `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRulesResponse) Reset() {
	*x = ListRulesResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRulesResponse) ProtoMessage() {}

func (x *ListRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRulesResponse.ProtoReflect.Descriptor instead.
func (*ListRulesResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{15}
}

func (x *ListRulesResponse) GetRules() []*Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ParseEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ChunkData     []byte                 `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3" json:"chunk_data,omitempty"` // Streaming data for large emails
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseEmailRequest) Reset() {
	*x = ParseEmailRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseEmailRequest) ProtoMessage() {}

func (x *ParseEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseEmailRequest.ProtoReflect.Descriptor instead.
func (*ParseEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{16}
}

func (x *ParseEmailRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ParseEmailRequest) GetChunkData() []byte {
	if x != nil {
		return x.ChunkData
	}
	return nil
}

type ParseEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailThread   *EmailThread           `protobuf:"bytes,1,opt,name=email_thread,json=emailThread,proto3" json:"email_thread,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParseEmailResponse) Reset() {
	*x = ParseEmailResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParseEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseEmailResponse) ProtoMessage() {}

func (x *ParseEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseEmailResponse.ProtoReflect.Descriptor instead.
func (*ParseEmailResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{17}
}

func (x *ParseEmailResponse) GetEmailThread() *EmailThread {
	if x != nil {
		return x.EmailThread
	}
	return nil
}

func (x *ParseEmailResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ParseEmailResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExtractThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         *EmailMessage          `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractThreadRequest) Reset() {
	*x = ExtractThreadRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractThreadRequest) ProtoMessage() {}

func (x *ExtractThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractThreadRequest.ProtoReflect.Descriptor instead.
func (*ExtractThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{18}
}

func (x *ExtractThreadRequest) GetEmail() *EmailMessage {
	if x != nil {
		return x.Email
	}
	return nil
}

type ExtractThreadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thread        *EmailThread           `protobuf:"bytes,1,opt,name=thread,proto3" json:"thread,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtractThreadResponse) Reset() {
	*x = ExtractThreadResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtractThreadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractThreadResponse) ProtoMessage() {}

func (x *ExtractThreadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractThreadResponse.ProtoReflect.Descriptor instead.
func (*ExtractThreadResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{19}
}

func (x *ExtractThreadResponse) GetThread() *EmailThread {
	if x != nil {
		return x.Thread
	}
	return nil
}

type GenerateReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuditId       string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	ReportData    *AuditReport           `protobuf:"bytes,2,opt,name=report_data,json=reportData,proto3" json:"report_data,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"` // Supported: json, pdf, html
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportRequest) Reset() {
	*x = GenerateReportRequest{}
	mi := &file_proto_email_audit_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportRequest) ProtoMessage() {}

func (x *GenerateReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportRequest.ProtoReflect.Descriptor instead.
func (*GenerateReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{20}
}

func (x *GenerateReportRequest) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *GenerateReportRequest) GetReportData() *AuditReport {
	if x != nil {
		return x.ReportData
	}
	return nil
}

func (x *GenerateReportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type GenerateReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportContent []byte                 `protobuf:"bytes,1,opt,name=report_content,json=reportContent,proto3" json:"report_content,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateReportResponse) Reset() {
	*x = GenerateReportResponse{}
	mi := &file_proto_email_audit_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateReportResponse) ProtoMessage() {}

func (x *GenerateReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateReportResponse.ProtoReflect.Descriptor instead.
func (*GenerateReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{21}
}

func (x *GenerateReportResponse) GetReportContent() []byte {
	if x != nil {
		return x.ReportContent
	}
	return nil
}

func (x *GenerateReportResponse) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *GenerateReportResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AuditReport struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AuditId         string                 `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CompanyId       string                 `protobuf:"bytes,3,opt,name=company_id,json=companyId,proto3" json:"company_id,omitempty"`
	OverallScore    float64                `protobuf:"fixed64,4,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	RuleEvaluations []*RuleEvaluation      `protobuf:"bytes,5,rep,name=rule_evaluations,json=ruleEvaluations,proto3" json:"rule_evaluations,omitempty"`
	Summary         string                 `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	EmailThread     *EmailThread           `protobuf:"bytes,8,opt,name=email_thread,json=emailThread,proto3" json:"email_thread,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuditReport) Reset() {
	*x = AuditReport{}
	mi := &file_proto_email_audit_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditReport) ProtoMessage() {}

func (x *AuditReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditReport.ProtoReflect.Descriptor instead.
func (*AuditReport) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{22}
}

func (x *AuditReport) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

func (x *AuditReport) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuditReport) GetCompanyId() string {
	if x != nil {
		return x.CompanyId
	}
	return ""
}

func (x *AuditReport) GetOverallScore() float64 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *AuditReport) GetRuleEvaluations() []*RuleEvaluation {
	if x != nil {
		return x.RuleEvaluations
	}
	return nil
}

func (x *AuditReport) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *AuditReport) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AuditReport) GetEmailThread() *EmailThread {
	if x != nil {
		return x.EmailThread
	}
	return nil
}

type EmailThread struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      string                 `protobuf:"bytes,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Messages      []*EmailMessage        `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"`
	Participants  []string               `protobuf:"bytes,4,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailThread) Reset() {
	*x = EmailThread{}
	mi := &file_proto_email_audit_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailThread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailThread) ProtoMessage() {}

func (x *EmailThread) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailThread.ProtoReflect.Descriptor instead.
func (*EmailThread) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{23}
}

func (x *EmailThread) GetThreadId() string {
	if x != nil {
		return x.ThreadId
	}
	return ""
}

func (x *EmailThread) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailThread) GetMessages() []*EmailMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *EmailThread) GetParticipants() []string {
	if x != nil {
		return x.Participants
	}
	return nil
}

type EmailMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            []string               `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	Cc            []string               `protobuf:"bytes,4,rep,name=cc,proto3" json:"cc,omitempty"`
	Subject       string                 `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	IsHtml        bool                   `protobuf:"varint,8,opt,name=is_html,json=isHtml,proto3" json:"is_html,omitempty"`
	Attachments   []byte                 `protobuf:"bytes,9,opt,name=attachments,proto3" json:"attachments,omitempty"` // Raw bytes of attachments (should be base64 if stored)
	Headers       map[string]string      `protobuf:"bytes,10,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailMessage) Reset() {
	*x = EmailMessage{}
	mi := &file_proto_email_audit_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailMessage) ProtoMessage() {}

func (x *EmailMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailMessage.ProtoReflect.Descriptor instead.
func (*EmailMessage) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{24}
}

func (x *EmailMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EmailMessage) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EmailMessage) GetTo() []string {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *EmailMessage) GetCc() []string {
	if x != nil {
		return x.Cc
	}
	return nil
}

func (x *EmailMessage) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *EmailMessage) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *EmailMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *EmailMessage) GetIsHtml() bool {
	if x != nil {
		return x.IsHtml
	}
	return false
}

func (x *EmailMessage) GetAttachments() []byte {
	if x != nil {
		return x.Attachments
	}
	return nil
}

func (x *EmailMessage) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type RuleEvaluation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuleId        string                 `protobuf:"bytes,1,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	RuleName      string                 `protobuf:"bytes,2,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Passed        bool                   `protobuf:"varint,6,opt,name=passed,proto3" json:"passed,omitempty"`
	Suggestions   []string               `protobuf:"bytes,7,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleEvaluation) Reset() {
	*x = RuleEvaluation{}
	mi := &file_proto_email_audit_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleEvaluation) ProtoMessage() {}

func (x *RuleEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleEvaluation.ProtoReflect.Descriptor instead.
func (*RuleEvaluation) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{25}
}

func (x *RuleEvaluation) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *RuleEvaluation) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

func (x *RuleEvaluation) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *RuleEvaluation) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RuleEvaluation) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *RuleEvaluation) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *RuleEvaluation) GetSuggestions() []string {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Weight        float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Type          RuleType               `protobuf:"varint,6,opt,name=type,proto3,enum=emailaudit.RuleType" json:"type,omitempty"`
	Config        *RuleConfig            `protobuf:"bytes,7,opt,name=config,proto3" json:"config,omitempty"`
	Enabled       bool                   `protobuf:"varint,8,opt,name=enabled,proto3" json:"enabled,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_proto_email_audit_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{26}
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Rule) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Rule) GetType() RuleType {
	if x != nil {
		return x.Type
	}
	return RuleType_REGEX_BASED
}

func (x *Rule) GetConfig() *RuleConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Rule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Rule) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Rule) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type RuleConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    map[string]string      `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Dynamic config for rule
	Keywords      []string               `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`                                                                               // Used for keyword-based rules
	RegexPattern  string                 `protobuf:"bytes,3,opt,name=regex_pattern,json=regexPattern,proto3" json:"regex_pattern,omitempty"`                                                   // Used for regex-based rules
	Threshold     float64                `protobuf:"fixed64,4,opt,name=threshold,proto3" json:"threshold,omitempty"`                                                                           // Used in ML-based rules
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuleConfig) Reset() {
	*x = RuleConfig{}
	mi := &file_proto_email_audit_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuleConfig) ProtoMessage() {}

func (x *RuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_email_audit_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuleConfig.ProtoReflect.Descriptor instead.
func (*RuleConfig) Descriptor() ([]byte, []int) {
	return file_proto_email_audit_proto_rawDescGZIP(), []int{27}
}

func (x *RuleConfig) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *RuleConfig) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *RuleConfig) GetRegexPattern() string {
	if x != nil {
		return x.RegexPattern
	}
	return ""
}

func (x *RuleConfig) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

var File_proto_email_audit_proto protoreflect.FileDescriptor

const file_proto_email_audit_proto_rawDesc = "" +
	"\n" +
	"\x17proto/email_audit.proto\x12\n" +
	"emailaudit\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x02\n" +
	"\x11EmailAuditRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bemail_id\x18\x02 \x01(\tR\aemailId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12#\n" +
	"\remail_content\x18\x05 \x01(\fR\femailContent\x12G\n" +
	"\bmetadata\x18\x06 \x03(\v2+.emailaudit.EmailAuditRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"a\n" +
	"\x12EmailAuditResponse\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"K\n" +
	"\x15GetAuditReportRequest\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"a\n" +
	"\x16GetAuditReportResponse\x12/\n" +
	"\x06report\x18\x01 \x01(\v2\x17.emailaudit.AuditReportR\x06report\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\x81\x01\n" +
	"\x16GetAuditSummaryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x9e\x01\n" +
	"\x17GetAuditSummaryResponse\x121\n" +
	"\areports\x18\x01 \x03(\v2\x17.emailaudit.AuditReportR\areports\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xb5\x01\n" +
	"\x16RulesEvaluationRequest\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\brule_set\x18\x03 \x03(\v2\x10.emailaudit.RuleR\aruleSet\x12:\n" +
	"\femail_thread\x18\x04 \x01(\v2\x17.emailaudit.EmailThreadR\vemailThread\"\x8a\x01\n" +
	"\x17RulesEvaluationResponse\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12<\n" +
	"\vevaluations\x18\x02 \x03(\v2\x1a.emailaudit.RuleEvaluationR\vevaluations\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"U\n" +
	"\x0eAddRuleRequest\x12$\n" +
	"\x04rule\x18\x01 \x01(\v2\x10.emailaudit.RuleR\x04rule\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\"B\n" +
	"\x0fAddRuleResponse\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"X\n" +
	"\x11UpdateRuleRequest\x12$\n" +
	"\x04rule\x18\x01 \x01(\v2\x10.emailaudit.RuleR\x04rule\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\",\n" +
	"\x12UpdateRuleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"K\n" +
	"\x11DeleteRuleRequest\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x02 \x01(\tR\tcompanyId\",\n" +
	"\x12DeleteRuleResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"p\n" +
	"\x10ListRulesRequest\x12\x1d\n" +
	"\n" +
	"company_id\x18\x01 \x01(\tR\tcompanyId\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12!\n" +
	"\fenabled_only\x18\x03 \x01(\bR\venabledOnly\";\n" +
	"\x11ListRulesResponse\x12&\n" +
	"\x05rules\x18\x01 \x03(\v2\x10.emailaudit.RuleR\x05rules\"Q\n" +
	"\x11ParseEmailRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fR\tchunkData\"\x8d\x01\n" +
	"\x12ParseEmailResponse\x12:\n" +
	"\femail_thread\x18\x01 \x01(\v2\x17.emailaudit.EmailThreadR\vemailThread\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"F\n" +
	"\x14ExtractThreadRequest\x12.\n" +
	"\x05email\x18\x01 \x01(\v2\x18.emailaudit.EmailMessageR\x05email\"H\n" +
	"\x15ExtractThreadResponse\x12/\n" +
	"\x06thread\x18\x01 \x01(\v2\x17.emailaudit.EmailThreadR\x06thread\"\x84\x01\n" +
	"\x15GenerateReportRequest\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x128\n" +
	"\vreport_data\x18\x02 \x01(\v2\x17.emailaudit.AuditReportR\n" +
	"reportData\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\"z\n" +
	"\x16GenerateReportResponse\x12%\n" +
	"\x0ereport_content\x18\x01 \x01(\fR\rreportContent\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"\xdd\x02\n" +
	"\vAuditReport\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"company_id\x18\x03 \x01(\tR\tcompanyId\x12#\n" +
	"\roverall_score\x18\x04 \x01(\x01R\foverallScore\x12E\n" +
	"\x10rule_evaluations\x18\x05 \x03(\v2\x1a.emailaudit.RuleEvaluationR\x0fruleEvaluations\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12:\n" +
	"\femail_thread\x18\b \x01(\v2\x17.emailaudit.EmailThreadR\vemailThread\"\x9e\x01\n" +
	"\vEmailThread\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\tR\bthreadId\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x124\n" +
	"\bmessages\x18\x03 \x03(\v2\x18.emailaudit.EmailMessageR\bmessages\x12\"\n" +
	"\fparticipants\x18\x04 \x03(\tR\fparticipants\"\x81\x03\n" +
	"\fEmailMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x03(\tR\x02to\x12\x0e\n" +
	"\x02cc\x18\x04 \x03(\tR\x02cc\x12\x18\n" +
	"\asubject\x18\x05 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x06 \x01(\tR\x04body\x128\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\ais_html\x18\b \x01(\bR\x06isHtml\x12 \n" +
	"\vattachments\x18\t \x01(\fR\vattachments\x12?\n" +
	"\aheaders\x18\n" +
	" \x03(\v2%.emailaudit.EmailMessage.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xca\x01\n" +
	"\x0eRuleEvaluation\x12\x17\n" +
	"\arule_id\x18\x01 \x01(\tR\x06ruleId\x12\x1b\n" +
	"\trule_name\x18\x02 \x01(\tR\bruleName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12\x16\n" +
	"\x06passed\x18\x06 \x01(\bR\x06passed\x12 \n" +
	"\vsuggestions\x18\a \x03(\tR\vsuggestions\"\xea\x02\n" +
	"\x04Rule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12(\n" +
	"\x04type\x18\x06 \x01(\x0e2\x14.emailaudit.RuleTypeR\x04type\x12.\n" +
	"\x06config\x18\a \x01(\v2\x16.emailaudit.RuleConfigR\x06config\x12\x18\n" +
	"\aenabled\x18\b \x01(\bR\aenabled\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xf2\x01\n" +
	"\n" +
	"RuleConfig\x12F\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2&.emailaudit.RuleConfig.ParametersEntryR\n" +
	"parameters\x12\x1a\n" +
	"\bkeywords\x18\x02 \x03(\tR\bkeywords\x12#\n" +
	"\rregex_pattern\x18\x03 \x01(\tR\fregexPattern\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x01R\tthreshold\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*N\n" +
	"\bRuleType\x12\x0f\n" +
	"\vREGEX_BASED\x10\x00\x12\f\n" +
	"\bML_BASED\x10\x01\x12\x11\n" +
	"\rKEYWORD_BASED\x10\x02\x12\x10\n" +
	"\fCUSTOM_LOGIC\x10\x032\x9c\x02\n" +
	"\x11EmailAuditService\x12R\n" +
	"\x11ProcessEmailAudit\x12\x1d.emailaudit.EmailAuditRequest\x1a\x1e.emailaudit.EmailAuditResponse\x12W\n" +
	"\x0eGetAuditReport\x12!.emailaudit.GetAuditReportRequest\x1a\".emailaudit.GetAuditReportResponse\x12Z\n" +
	"\x0fGetAuditSummary\x12\".emailaudit.GetAuditSummaryRequest\x1a#.emailaudit.GetAuditSummaryResponse2\x96\x03\n" +
	"\x12RulesEngineService\x12X\n" +
	"\rEvaluateRules\x12\".emailaudit.RulesEvaluationRequest\x1a#.emailaudit.RulesEvaluationResponse\x12B\n" +
	"\aAddRule\x12\x1a.emailaudit.AddRuleRequest\x1a\x1b.emailaudit.AddRuleResponse\x12K\n" +
	"\n" +
	"UpdateRule\x12\x1d.emailaudit.UpdateRuleRequest\x1a\x1e.emailaudit.UpdateRuleResponse\x12K\n" +
	"\n" +
	"DeleteRule\x12\x1d.emailaudit.DeleteRuleRequest\x1a\x1e.emailaudit.DeleteRuleResponse\x12H\n" +
	"\tListRules\x12\x1c.emailaudit.ListRulesRequest\x1a\x1d.emailaudit.ListRulesResponse2\xbd\x01\n" +
	"\x16EmailProcessingService\x12M\n" +
	"\n" +
	"ParseEmail\x12\x1d.emailaudit.ParseEmailRequest\x1a\x1e.emailaudit.ParseEmailResponse(\x01\x12T\n" +
	"\rExtractThread\x12 .emailaudit.ExtractThreadRequest\x1a!.emailaudit.ExtractThreadResponse2r\n" +
	"\x17ReportGenerationService\x12W\n" +
	"\x0eGenerateReport\x12!.emailaudit.GenerateReportRequest\x1a\".emailaudit.GenerateReportResponseB1Z/github.com/ankittk/email-audit-service/proto;pbb\x06proto3"

var (
	file_proto_email_audit_proto_rawDescOnce sync.Once
	file_proto_email_audit_proto_rawDescData []byte
)

func file_proto_email_audit_proto_rawDescGZIP() []byte {
	file_proto_email_audit_proto_rawDescOnce.Do(func() {
		file_proto_email_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_email_audit_proto_rawDesc), len(file_proto_email_audit_proto_rawDesc)))
	})
	return file_proto_email_audit_proto_rawDescData
}

var file_proto_email_audit_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_email_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_email_audit_proto_goTypes = []any{
	(RuleType)(0),                   // 0: emailaudit.RuleType
	(*EmailAuditRequest)(nil),       // 1: emailaudit.EmailAuditRequest
	(*EmailAuditResponse)(nil),      // 2: emailaudit.EmailAuditResponse
	(*GetAuditReportRequest)(nil),   // 3: emailaudit.GetAuditReportRequest
	(*GetAuditReportResponse)(nil),  // 4: emailaudit.GetAuditReportResponse
	(*GetAuditSummaryRequest)(nil),  // 5: emailaudit.GetAuditSummaryRequest
	(*GetAuditSummaryResponse)(nil), // 6: emailaudit.GetAuditSummaryResponse
	(*RulesEvaluationRequest)(nil),  // 7: emailaudit.RulesEvaluationRequest
	(*RulesEvaluationResponse)(nil), // 8: emailaudit.RulesEvaluationResponse
	(*AddRuleRequest)(nil),          // 9: emailaudit.AddRuleRequest
	(*AddRuleResponse)(nil),         // 10: emailaudit.AddRuleResponse
	(*UpdateRuleRequest)(nil),       // 11: emailaudit.UpdateRuleRequest
	(*UpdateRuleResponse)(nil),      // 12: emailaudit.UpdateRuleResponse
	(*DeleteRuleRequest)(nil),       // 13: emailaudit.DeleteRuleRequest
	(*DeleteRuleResponse)(nil),      // 14: emailaudit.DeleteRuleResponse
	(*ListRulesRequest)(nil),        // 15: emailaudit.ListRulesRequest
	(*ListRulesResponse)(nil),       // 16: emailaudit.ListRulesResponse
	(*ParseEmailRequest)(nil),       // 17: emailaudit.ParseEmailRequest
	(*ParseEmailResponse)(nil),      // 18: emailaudit.ParseEmailResponse
	(*ExtractThreadRequest)(nil),    // 19: emailaudit.ExtractThreadRequest
	(*ExtractThreadResponse)(nil),   // 20: emailaudit.ExtractThreadResponse
	(*GenerateReportRequest)(nil),   // 21: emailaudit.GenerateReportRequest
	(*GenerateReportResponse)(nil),  // 22: emailaudit.GenerateReportResponse
	(*AuditReport)(nil),             // 23: emailaudit.AuditReport
	(*EmailThread)(nil),             // 24: emailaudit.EmailThread
	(*EmailMessage)(nil),            // 25: emailaudit.EmailMessage
	(*RuleEvaluation)(nil),          // 26: emailaudit.RuleEvaluation
	(*Rule)(nil),                    // 27: emailaudit.Rule
	(*RuleConfig)(nil),              // 28: emailaudit.RuleConfig
	nil,                             // 29: emailaudit.EmailAuditRequest.MetadataEntry
	nil,                             // 30: emailaudit.EmailMessage.HeadersEntry
	nil,                             // 31: emailaudit.RuleConfig.ParametersEntry
	(*timestamppb.Timestamp)(nil),   // 32: google.protobuf.Timestamp
}
var file_proto_email_audit_proto_depIdxs = []int32{
	32, // 0: emailaudit.EmailAuditRequest.timestamp:type_name -> google.protobuf.Timestamp
	29, // 1: emailaudit.EmailAuditRequest.metadata:type_name -> emailaudit.EmailAuditRequest.MetadataEntry
	23, // 2: emailaudit.GetAuditReportResponse.report:type_name -> emailaudit.AuditReport
	23, // 3: emailaudit.GetAuditSummaryResponse.reports:type_name -> emailaudit.AuditReport
	27, // 4: emailaudit.RulesEvaluationRequest.rule_set:type_name -> emailaudit.Rule
	24, // 5: emailaudit.RulesEvaluationRequest.email_thread:type_name -> emailaudit.EmailThread
	26, // 6: emailaudit.RulesEvaluationResponse.evaluations:type_name -> emailaudit.RuleEvaluation
	27, // 7: emailaudit.AddRuleRequest.rule:type_name -> emailaudit.Rule
	27, // 8: emailaudit.UpdateRuleRequest.rule:type_name -> emailaudit.Rule
	27, // 9: emailaudit.ListRulesResponse.rules:type_name -> emailaudit.Rule
	24, // 10: emailaudit.ParseEmailResponse.email_thread:type_name -> emailaudit.EmailThread
	25, // 11: emailaudit.ExtractThreadRequest.email:type_name -> emailaudit.EmailMessage
	24, // 12: emailaudit.ExtractThreadResponse.thread:type_name -> emailaudit.EmailThread
	23, // 13: emailaudit.GenerateReportRequest.report_data:type_name -> emailaudit.AuditReport
	26, // 14: emailaudit.AuditReport.rule_evaluations:type_name -> emailaudit.RuleEvaluation
	32, // 15: emailaudit.AuditReport.created_at:type_name -> google.protobuf.Timestamp
	24, // 16: emailaudit.AuditReport.email_thread:type_name -> emailaudit.EmailThread
	25, // 17: emailaudit.EmailThread.messages:type_name -> emailaudit.EmailMessage
	32, // 18: emailaudit.EmailMessage.timestamp:type_name -> google.protobuf.Timestamp
	30, // 19: emailaudit.EmailMessage.headers:type_name -> emailaudit.EmailMessage.HeadersEntry
	0,  // 20: emailaudit.Rule.type:type_name -> emailaudit.RuleType
	28, // 21: emailaudit.Rule.config:type_name -> emailaudit.RuleConfig
	32, // 22: emailaudit.Rule.created_at:type_name -> google.protobuf.Timestamp
	32, // 23: emailaudit.Rule.updated_at:type_name -> google.protobuf.Timestamp
	31, // 24: emailaudit.RuleConfig.parameters:type_name -> emailaudit.RuleConfig.ParametersEntry
	1,  // 25: emailaudit.EmailAuditService.ProcessEmailAudit:input_type -> emailaudit.EmailAuditRequest
	3,  // 26: emailaudit.EmailAuditService.GetAuditReport:input_type -> emailaudit.GetAuditReportRequest
	5,  // 27: emailaudit.EmailAuditService.GetAuditSummary:input_type -> emailaudit.GetAuditSummaryRequest
	7,  // 28: emailaudit.RulesEngineService.EvaluateRules:input_type -> emailaudit.RulesEvaluationRequest
	9,  // 29: emailaudit.RulesEngineService.AddRule:input_type -> emailaudit.AddRuleRequest
	11, // 30: emailaudit.RulesEngineService.UpdateRule:input_type -> emailaudit.UpdateRuleRequest
	13, // 31: emailaudit.RulesEngineService.DeleteRule:input_type -> emailaudit.DeleteRuleRequest
	15, // 32: emailaudit.RulesEngineService.ListRules:input_type -> emailaudit.ListRulesRequest
	17, // 33: emailaudit.EmailProcessingService.ParseEmail:input_type -> emailaudit.ParseEmailRequest
	19, // 34: emailaudit.EmailProcessingService.ExtractThread:input_type -> emailaudit.ExtractThreadRequest
	21, // 35: emailaudit.ReportGenerationService.GenerateReport:input_type -> emailaudit.GenerateReportRequest
	2,  // 36: emailaudit.EmailAuditService.ProcessEmailAudit:output_type -> emailaudit.EmailAuditResponse
	4,  // 37: emailaudit.EmailAuditService.GetAuditReport:output_type -> emailaudit.GetAuditReportResponse
	6,  // 38: emailaudit.EmailAuditService.GetAuditSummary:output_type -> emailaudit.GetAuditSummaryResponse
	8,  // 39: emailaudit.RulesEngineService.EvaluateRules:output_type -> emailaudit.RulesEvaluationResponse
	10, // 40: emailaudit.RulesEngineService.AddRule:output_type -> emailaudit.AddRuleResponse
	12, // 41: emailaudit.RulesEngineService.UpdateRule:output_type -> emailaudit.UpdateRuleResponse
	14, // 42: emailaudit.RulesEngineService.DeleteRule:output_type -> emailaudit.DeleteRuleResponse
	16, // 43: emailaudit.RulesEngineService.ListRules:output_type -> emailaudit.ListRulesResponse
	18, // 44: emailaudit.EmailProcessingService.ParseEmail:output_type -> emailaudit.ParseEmailResponse
	20, // 45: emailaudit.EmailProcessingService.ExtractThread:output_type -> emailaudit.ExtractThreadResponse
	22, // 46: emailaudit.ReportGenerationService.GenerateReport:output_type -> emailaudit.GenerateReportResponse
	36, // [36:47] is the sub-list for method output_type
	25, // [25:36] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_email_audit_proto_init() }
func file_proto_email_audit_proto_init() {
	if File_proto_email_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_email_audit_proto_rawDesc), len(file_proto_email_audit_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_proto_email_audit_proto_goTypes,
		DependencyIndexes: file_proto_email_audit_proto_depIdxs,
		EnumInfos:         file_proto_email_audit_proto_enumTypes,
		MessageInfos:      file_proto_email_audit_proto_msgTypes,
	}.Build()
	File_proto_email_audit_proto = out.File
	file_proto_email_audit_proto_goTypes = nil
	file_proto_email_audit_proto_depIdxs = nil
}
